/*
* IntraChat 
* 
* Form Settings
* 
* This file is part of the IntraChat project
* This form show all the application settings
* 
* Copyright (C) 2012  Stefano BARILETTI <hackaroth@gmail.com>

* This program is free software: you can redistribute it and/or modify it under the 
* terms of the GNU General Public License as published by the Free Software 
* Foundation, either version 3 of the License, or (at your option) any later version.

* This program is distributed in the hope that it will be useful, but WITHOUT ANY 
* WARRANTY; without even the implied warranty of MERCHANTABILITY or 
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
* for more details.

* You should have received a copy of the GNU General Public License along with
* this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package intrachat;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

public class FormSettings extends javax.swing.JDialog {

    /**
     * Creates new form FormSettings
     */
    
    private OnSettingsChangedHandler onSettingsChanged;
    
    public FormSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setWindowsPosition();
        
        onSettingsChanged = null;
        
        if (!Settings.getUserIcon().isEmpty()) {
            String[] _userIcon = Settings.getUserIcon().split(";");

            if (_userIcon != null && _userIcon.length == 2) {
                cmbSex.setSelectedItem(_userIcon[0]);
                cmbIconName.setSelectedItem(_userIcon[1]);
                String path = "resources/images/users/" + _userIcon[0] + "/" + _userIcon[1];
                java.net.URL imgURL = getClass().getResource(path);

                if (imgURL != null) {
                    ImageIcon icon = new ImageIcon(imgURL);
                    lblUserIcon.setIcon(icon);
                }            
            }
        }
        
        edtPort.setText(String.valueOf(Settings.getPort()));
        edtUserName.setText(Settings.getMyName());
        
        String _notifySound = Settings.getNotifySoundFileName();
        
        if (_notifySound.isEmpty()) {
            _notifySound = "No sound";
            btnPLaySound.setEnabled(false);
        }
        else
            btnPLaySound.setEnabled(true);
        
        cmbPLaySound.setSelectedItem(_notifySound);
        
        edtStartScanRange.setText(String.valueOf(Settings.getStartScanRange()));
        edtEndScanRange.setText(String.valueOf(Settings.getEndScanRange()));
        
        String _myIpAddress = Settings.getLocalIpAddress();
        String[] _partOfIp  = _myIpAddress.split("\\.");
        String _ipClient = _partOfIp[0] + "." + _partOfIp[1] + "." + _partOfIp[2] + ".";
        
        lblIpAddress.setText(_ipClient);
    }

    public void setOnSettingsChangedHandler(OnSettingsChangedHandler onSettingsChanged) {
        this.onSettingsChanged = onSettingsChanged;
    }
    
    private void setWindowsPosition() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        this.setLocation(x, y);        
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlaySound = new javax.swing.JLabel();
        edtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPLaySound = new javax.swing.JComboBox();
        btnPLaySound = new javax.swing.JButton();
        edtTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        edtPort = new javax.swing.JFormattedTextField();
        lblScanRange = new javax.swing.JLabel();
        edtStartScanRange = new javax.swing.JFormattedTextField();
        edtEndScanRange = new javax.swing.JFormattedTextField();
        lblPlaySound2 = new javax.swing.JLabel();
        lblScanRange1 = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox();
        cmbIconName = new javax.swing.JComboBox();
        lblIpAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblPlaySound.setText("Play sound on incoming message:");

        lblUserName.setText("User name:");

        jLabel2.setText("Listen on port:");

        cmbPLaySound.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No sound", "bbm.wav", "express.wav", "glass.wav", "msg.wav", "new.wav", "notify.wav" }));
        cmbPLaySound.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPLaySoundItemStateChanged(evt);
            }
        });

        btnPLaySound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intrachat/resources/images/Play.png"))); // NOI18N
        btnPLaySound.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPLaySound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPLaySoundMouseClicked(evt);
            }
        });
        btnPLaySound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLaySoundActionPerformed(evt);
            }
        });

        edtTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        edtTitle.setText("Settings");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intrachat/resources/images/Save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        edtPort.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        lblScanRange.setText("Autoscan range:");

        edtStartScanRange.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        edtEndScanRange.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        lblPlaySound2.setText("/");

        lblScanRange1.setText("User icon:");

        lblUserIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.blue));
        lblUserIcon.setPreferredSize(new java.awt.Dimension(64, 64));

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cmbSex.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSexItemStateChanged(evt);
            }
        });

        cmbIconName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Barbarian.png", "Catholic.png", "Client.png", "Firefighter.png", "Graduate.png", "Muslim.png", "Santaclaus.png", "Teacher.png", "User1.png", "User2.png", "User3.png", "User4.png", "User5.png", "Viking.png", "Western.png" }));
        cmbIconName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbIconNameItemStateChanged(evt);
            }
        });

        lblIpAddress.setText("0.0.0.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblPlaySound)
                            .addComponent(lblUserName)
                            .addComponent(lblScanRange, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblScanRange1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbIconName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(edtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbPLaySound, 0, 218, Short.MAX_VALUE)
                                                .addGap(0, 0, 0)
                                                .addComponent(btnPLaySound, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblIpAddress)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(edtStartScanRange, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPlaySound2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(edtEndScanRange, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(edtPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edtTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUserIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbIconName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(edtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblScanRange1)
                        .addGap(60, 60, 60)
                        .addComponent(lblUserName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPLaySound, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPLaySound, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlaySound))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtEndScanRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlaySound2)
                    .addComponent(edtStartScanRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIpAddress)
                    .addComponent(lblScanRange))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPLaySoundItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPLaySoundItemStateChanged
        boolean _enabled = ((String)evt.getItem()).equals("No sound");
        btnPLaySound.setEnabled(!_enabled);
    }//GEN-LAST:event_cmbPLaySoundItemStateChanged

    private void btnPLaySoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPLaySoundMouseClicked
        Sounds.play((String)cmbPLaySound.getSelectedItem());
    }//GEN-LAST:event_btnPLaySoundMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!edtPort.getText().toString().isEmpty() && !edtUserName.getText().toString().isEmpty()) {
            Settings.setPort(Integer.valueOf(edtPort.getText().toString()));
            
            if (edtUserName.getText().toString().length() > 30)
                Settings.setMyName(edtUserName.getText().toString().substring(0, 30));
            else
                Settings.setMyName(edtUserName.getText().toString());
            
            String _sound = (String) cmbPLaySound.getSelectedItem();
            
            if (_sound.equals("No sound"))
                _sound = "";
            
            Settings.setNotifySoundFileName(_sound);
            
            int _startScanRange = -1;
            int _endScanRange = -1;
            
            if (!edtStartScanRange.getText().toString().isEmpty()) {
                _startScanRange = Integer.valueOf(edtStartScanRange.getText().toString());
            }
            
            if (!edtEndScanRange.getText().toString().isEmpty()) {
                _endScanRange = Integer.valueOf(edtEndScanRange.getText().toString());
            }
            
            if ((_startScanRange > 0 && _startScanRange < 255) && _endScanRange > 0 && _endScanRange < 255 && _startScanRange <= _endScanRange) {
                Settings.setStartScanRange(_startScanRange);
                Settings.setEndScanRange(_endScanRange);
            }

            String _sex = (String)cmbSex.getSelectedItem();
            String _iconName = (String)cmbIconName.getSelectedItem();

            if (!_sex.isEmpty() && !_iconName.isEmpty()) {
                String _icon = _sex + ";" + _iconName;
                Settings.setUserIcon(_icon);
            }
            
            Settings.Save();
            
            if (onSettingsChanged != null)
                onSettingsChanged.OnSettingsChanged();
            
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPLaySoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLaySoundActionPerformed
    }//GEN-LAST:event_btnPLaySoundActionPerformed

    private void cmbSexItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSexItemStateChanged
        String _sex = (String)evt.getItem();
        String _iconName = (String)cmbIconName.getSelectedItem();

        String path = "resources/images/users/" + _sex + "/" +_iconName;
        java.net.URL imgURL = getClass().getResource(path);

        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            lblUserIcon.setIcon(icon);
        } 
    }//GEN-LAST:event_cmbSexItemStateChanged

    private void cmbIconNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbIconNameItemStateChanged
        String _sex = (String)cmbSex.getSelectedItem();
        String _iconName = (String)evt.getItem();

        String path = "resources/images/users/" + _sex + "/" +_iconName;
        java.net.URL imgURL = getClass().getResource(path);

        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            lblUserIcon.setIcon(icon);
        }     }//GEN-LAST:event_cmbIconNameItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormSettings dialog = new FormSettings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPLaySound;
    private javax.swing.JComboBox cmbIconName;
    private javax.swing.JComboBox cmbPLaySound;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JFormattedTextField edtEndScanRange;
    private javax.swing.JFormattedTextField edtPort;
    private javax.swing.JFormattedTextField edtStartScanRange;
    private javax.swing.JLabel edtTitle;
    private javax.swing.JTextField edtUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIpAddress;
    private javax.swing.JLabel lblPlaySound;
    private javax.swing.JLabel lblPlaySound2;
    private javax.swing.JLabel lblScanRange;
    private javax.swing.JLabel lblScanRange1;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
