/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class intrachat_PingICMP */

#ifndef _Included_intrachat_PingICMP
#define _Included_intrachat_PingICMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     intrachat_PingICMP
 * Method:    isReachable
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_intrachat_PingICMP_isReachable
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
